### ISSUE TITLE
[Issue]: gfx1150 comfyui lockup with GCVM_L2_PROTECTION_FAULT_STATUS, MES failed to respond to msg=REMOVE_QUEUE

### ISSUE THREAD

**Issue by dattrax** [ROCm/TheRock#1271]
### Problem Description

Running WAN2.2 or QWEN results in a GPU lockup

I've tried running hipblaslt-test and this is OK.  WAN2.1 is also OK.

I've a AMD coredump available, but I'm not sure how to debug further.

### Operating System

Fedora Linux 43 (rawhide)

### CPU

AMD Ryzen AI 9 HX 370 w/ Radeon 890M

### GPU

AMD Ryzen AI 9 HX 370 w/ Radeon 890M (gfx1150)

### ROCm Version

Nightly (11739e9) git tag for reference

### Steps to Reproduce

Build TheRock + pytorch for gfx1150 & install

Install comfyui + WAN2.2

Run a prompt

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.18
Runtime Ext Version:     1.11
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
XNACK enabled:           NO
DMAbuf Support:          YES
VMM Support:             YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen AI 9 HX 370 w/ Radeon 890M
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen AI 9 HX 370 w/ Radeon 890M
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      49152(0xc000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   5157                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            24                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    65608740(0x3e91c24) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    65608740(0x3e91c24) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    65608740(0x3e91c24) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 4                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65608740(0x3e91c24) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1150                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon Graphics                
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      2048(0x800) KB                     
  Chip ID:                 5390(0x150e)                       
  ASIC Revision:           4(0x4)                             
  Cacheline Size:          128(0x80)                          
  Max Clock Freq. (MHz):   2900                               
  BDFID:                   49408                              
  Internal Node ID:        1                                  
  Compute Unit:            16                                 
  SIMDs per CU:            2                                  
  Shader Engines:          1                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       APU
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        2147483647(0x7fffffff)             
    y                        65535(0xffff)                      
    z                        65535(0xffff)                      
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 31                                 
  SDMA engine uCode::      14                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    67108864(0x4000000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    67108864(0x4000000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1150         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
    ISA 2                    
      Name:                    amdgcn-amd-amdhsa--gfx11-generic   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    aie2                               
  Uuid:                    AIE-XX                             
  Marketing Name:          AIE-ML                             
  Vendor Name:             AMD                                
  Feature:                 AGENT_DISPATCH                     
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        1(0x1)                             
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          64(0x40)                           
  Queue Type:              SINGLE                             
  Node:                    0                                  
  Device Type:             DSP                                
  Cache Info:              
    L2:                      2048(0x800) KB                     
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          0(0x0)                             
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            0                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:0                                  
  Memory Properties:       
  Features:                AGENT_DISPATCH
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, COARSE GRAINED
      Size:                    65608740(0x3e91c24) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65536(0x10000) KB                  
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65608740(0x3e91c24) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*** Done *** 

### Additional Information

[ 1552.620116] amdgpu 0000:c1:00.0: amdgpu: Dumping IP State
[ 1552.620989] amdgpu 0000:c1:00.0: amdgpu: Dumping IP State Completed
[ 1552.621050] amdgpu 0000:c1:00.0: amdgpu: [drm] AMDGPU device coredump file has been created
[ 1552.621052] amdgpu 0000:c1:00.0: amdgpu: [drm] Check your /sys/class/drm/card1/device/devcoredump/data
[ 1552.621053] amdgpu 0000:c1:00.0: amdgpu: ring gfx_0.0.0 timeout, signaled seq=25933, emitted seq=25934
[ 1552.621056] amdgpu 0000:c1:00.0: amdgpu: Process ptyxis pid 4049 thread ptyxis pid 4049
[ 1552.621058] amdgpu 0000:c1:00.0: amdgpu: Starting gfx_0.0.0 ring reset
[ 1554.624900] amdgpu 0000:c1:00.0: amdgpu: MES failed to respond to msg=RESET
[ 1554.624907] amdgpu 0000:c1:00.0: amdgpu: failed to reset legacy queue
[ 1554.624909] amdgpu 0000:c1:00.0: amdgpu: reset via MES failed and try pipe reset -110
[ 1554.624911] amdgpu 0000:c1:00.0: amdgpu: The CPFW hasn’t support pipe reset yet.
[ 1554.624912] amdgpu 0000:c1:00.0: amdgpu: Ring gfx_0.0.0 reset failed
[ 1554.624915] amdgpu 0000:c1:00.0: amdgpu: GPU reset begin!
[ 1554.624943] amdgpu 0000:c1:00.0: amdgpu: Failed to evict queue 2
[ 1554.624944] amdgpu 0000:c1:00.0: amdgpu: Failed to evict queue 1
[ 1554.624946] amdgpu 0000:c1:00.0: amdgpu: Failed to evict queue 0
[ 1554.624947] amdgpu: Failed to suspend process pid 5742
[ 1554.628612] [drm:amdgpu_cs_ioctl [amdgpu]] ERROR Failed to initialize parser -125!
[ 1556.714994] amdgpu 0000:c1:00.0: amdgpu: MES failed to respond to msg=REMOVE_QUEUE
[ 1556.715002] amdgpu 0000:c1:00.0: amdgpu: failed to unmap legacy queue
[ 1557.022593] [drm:gfx_v11_0_hw_fini [amdgpu]] ERROR failed to halt cp gfx
[ 1557.024089] amdgpu 0000:c1:00.0: amdgpu: MODE2 reset
[ 1557.046205] amdgpu 0000:c1:00.0: amdgpu: GPU reset succeeded, trying to resume
[ 1557.046541] [drm] PCIE GART of 512M enabled (table at 0x0000008000F00000).
[ 1557.046584] amdgpu 0000:c1:00.0: amdgpu: SMU is resuming…
[ 1557.050724] amdgpu 0000:c1:00.0: amdgpu: SMU is resumed successfully!
[ 1557.060042] amdgpu 0000:c1:00.0: amdgpu: [drm] DMUB hardware initialized: version=0x09002600
[ 1557.233262] amdgpu 0000:c1:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
[ 1557.233273] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
[ 1557.233275] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
[ 1557.233277] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 6 on hub 0
[ 1557.233278] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 7 on hub 0
[ 1557.233279] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 8 on hub 0
[ 1557.233280] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 9 on hub 0
[ 1557.233282] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 10 on hub 0
[ 1557.233283] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 11 on hub 0
[ 1557.233284] amdgpu 0000:c1:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
[ 1557.233286] amdgpu 0000:c1:00.0: amdgpu: ring vcn_unified_0 uses VM inv eng 0 on hub 8
[ 1557.233287] amdgpu 0000:c1:00.0: amdgpu: ring jpeg_dec_0 uses VM inv eng 1 on hub 8
[ 1557.233288] amdgpu 0000:c1:00.0: amdgpu: ring mes_kiq_3.1.0 uses VM inv eng 13 on hub 0
[ 1557.233290] amdgpu 0000:c1:00.0: amdgpu: ring vpe uses VM inv eng 4 on hub 8
[ 1557.249872] amdgpu 0000:c1:00.0: amdgpu: GPU reset(1) succeeded!
[ 1557.249885] amdgpu 0000:c1:00.0: [drm] device wedged, but recovered through reset

**Comment by schung-amd** [comment]
Hi @dattrax, this looks similar to some other hangs/TDRs we're looking into on gfx1150 and gfx1151. What is your `linux-firmware` version? There were some gfx1150- and gfx1151-specific fixes that made their way into version `20240318.git3b128b60-0ubuntu2.17` that might help with this.

**Comment by dattrax** [comment]
Do you know the fedora version of this firmware package and I’ll check?

**Comment by schung-amd** [comment]
Ah, didn't see you're on Fedora, sorry. It doesn't seem like Fedora has an up-to-date build, so this should be raised to the Fedora `linux-firmware` maintainers. 

I think it might be possible to manually replace the `amdgpu` firmware files on your system with the up-to-date ones at https://gitlab.com/kernel-firmware/linux-firmware (some similar guidance [here](https://discussion.fedoraproject.org/t/how-to-add-a-firmware-file-manually-to-fedora-35/74301)), but I wouldn't recommend doing so (unless you have experience doing this already) as it's better to get this fixed in the Fedora package unless you need support ASAP. I can try to provide further guidance on this if desired.

**Comment by dattrax** [comment]
I have firmware in /usr/lib/firmware/amdgpu/ that got installed as part of fedora42.

Package "linux-firmware-20250808-1.fc42.noarch" is already installed.
Package "amd-gpu-firmware-20250808-1.fc42.noarch" is already installed.

I don't know how to correlate between whats in 20240318.git3b128b60-0ubuntu2.1 and the above

I've moved from strix point to strix halo now, but am still getting issues.  My current crash is in dmesg with 

[ 7741.934070] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32780)
[ 7741.934078] amdgpu 0000:c2:00.0: amdgpu:  in process python pid 25454 thread python pid 25454)
[ 7741.934080] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f0a0eb94000 from client 10
[ 7741.934082] amdgpu 0000:c2:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00801031
[ 7741.934083] amdgpu 0000:c2:00.0: amdgpu: 	 Faulty UTCL2 client ID: TCP (0x8)
[ 7741.934084] amdgpu 0000:c2:00.0: amdgpu: 	 MORE_FAULTS: 0x1
[ 7741.934084] amdgpu 0000:c2:00.0: amdgpu: 	 WALKER_ERROR: 0x0
[ 7741.934085] amdgpu 0000:c2:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x3
[ 7741.934086] amdgpu 0000:c2:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
[ 7741.934086] amdgpu 0000:c2:00.0: amdgpu: 	 RW: 0x0

And it kills me back to the login screen.

**Comment by schung-amd** [comment]
My assumption is that the fix is not in that Fedora package, judging from the 20250808 date on those and the comment dates on https://bugs.launchpad.net/ubuntu/+source/linux-firmware/+bug/2117463 being after that. I'll try to verify that and find a simple workaround on non-Ubuntu distros if possible.

**Comment by dattrax** [comment]
Is there anyway to find out what firmware you have installed?

**Comment by schung-amd** [comment]
I assume from the 20250808 tag on the Fedora package that it's built from https://gitlab.com/kernel-firmware/linux-firmware/-/commits/20250808. There are a number of firmware fixes in https://gitlab.com/kernel-firmware/linux-firmware/-/commits/20250917. The 20250917 release on Arch fixes a similar problem with gfx1151, and I think it will also fix this gfx1150 issue. I presume that a 20250917 version of the Fedora package will be released at some point, but I don't know what the cadence of the Fedora package releases is.

**Comment by schung-amd** [comment]
Another thing to note is that there were some `rocm-libraries` commits for gfx1150 and gfx1151 support (e.g. https://github.com/ROCm/rocm-libraries/pull/697), but the nightly in your original report should be recent enough to include these.

**Comment by dattrax** [comment]
I'll try rebuilding.  I'm guessing I can just pull the firmware blobs from linux-firmare.git and replace them locally to get the latest (so I don't need to wait for the maintainers to make a new package)

**Comment by schung-amd** [comment]
There's a new rawhide package which should contain the firmware updates: https://packages.fedoraproject.org/pkgs/linux-firmware/linux-firmware/fedora-rawhide.html

**Comment by dattrax** [comment]
I've pulled the HoT version and the latest firmware on fedora rawhide and am still getting the same sort of crash on WAN2.2 (as before WAN2.1 works OK)

[ 6687.275264] amdgpu: init_user_pages: Failed to get user pages: -1
[ 6687.275338] amdgpu: init_user_pages: Failed to get user pages: -1
[ 6687.296324] amdgpu: init_user_pages: Failed to get user pages: -1
[ 6687.296428] amdgpu: init_user_pages: Failed to get user pages: -1
[ 7227.276797] hid-generic 0003:32AC:0002.0007: hiddev96,hidraw0: USB HID v1.11 Device [Framework HDMI Expansion Card] on usb-0000:c3:00.0-1/input1
[ 8086.277409] amdgpu 0000:c1:00.0: amdgpu: Dumping IP State
[ 8086.281831] amdgpu 0000:c1:00.0: amdgpu: Dumping IP State Completed
[ 8086.281897] amdgpu 0000:c1:00.0: amdgpu: [drm] AMDGPU device coredump file has been created
[ 8086.281903] amdgpu 0000:c1:00.0: amdgpu: [drm] Check your /sys/class/drm/card1/device/devcoredump/data
[ 8086.281905] amdgpu 0000:c1:00.0: amdgpu: ring gfx_0.0.0 timeout, signaled seq=131878, emitted seq=131880
[ 8086.281908] amdgpu 0000:c1:00.0: amdgpu:  Process gnome-shell pid 1971 thread gnome-shel:cs0 pid 2014
[ 8086.281911] amdgpu 0000:c1:00.0: amdgpu: Starting gfx_0.0.0 ring reset
[ 8088.285737] amdgpu 0000:c1:00.0: amdgpu: MES failed to respond to msg=RESET
[ 8088.285746] amdgpu 0000:c1:00.0: amdgpu: failed to reset legacy queue
[ 8088.285749] amdgpu 0000:c1:00.0: amdgpu: reset via MES failed and try pipe reset -110
[ 8088.285751] amdgpu 0000:c1:00.0: amdgpu: The CPFW hasn't support pipe reset yet.
[ 8088.285752] amdgpu 0000:c1:00.0: amdgpu: Ring gfx_0.0.0 reset failed
[ 8088.285755] amdgpu 0000:c1:00.0: amdgpu: GPU reset begin!
[ 8088.285765] amdgpu 0000:c1:00.0: amdgpu: Failed to evict queue 2
[ 8088.285767] amdgpu 0000:c1:00.0: amdgpu: Failed to evict queue 1
[ 8088.285768] amdgpu 0000:c1:00.0: amdgpu: Failed to evict queue 0
[ 8088.285769] amdgpu: Failed to suspend process pid 9305
[ 8090.292804] amdgpu 0000:c1:00.0: amdgpu: MES failed to respond to msg=REMOVE_QUEUE
[ 8090.292815] amdgpu 0000:c1:00.0: amdgpu: failed to unmap legacy queue
[ 8090.512005] [drm:gfx_v11_0_hw_fini [amdgpu]] *ERROR* failed to halt cp gfx
[ 8090.513463] amdgpu 0000:c1:00.0: amdgpu: MODE2 reset
[ 8090.535131] amdgpu 0000:c1:00.0: amdgpu: GPU reset succeeded, trying to resume
[ 8090.535497] [drm] PCIE GART of 512M enabled (table at 0x0000008000F00000).
[ 8090.535565] amdgpu 0000:c1:00.0: amdgpu: SMU is resuming...
[ 8090.539566] amdgpu 0000:c1:00.0: amdgpu: SMU is resumed successfully!
[ 8090.557642] amdgpu 0000:c1:00.0: amdgpu: [drm] DMUB hardware initialized: version=0x09002C01
[ 8090.566129] amdgpu 0000:c1:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
[ 8090.566132] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
[ 8090.566132] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
[ 8090.566133] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 6 on hub 0
[ 8090.566133] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 7 on hub 0
[ 8090.566134] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 8 on hub 0
[ 8090.566134] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 9 on hub 0
[ 8090.566135] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 10 on hub 0
[ 8090.566136] amdgpu 0000:c1:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 11 on hub 0
[ 8090.566136] amdgpu 0000:c1:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
[ 8090.566137] amdgpu 0000:c1:00.0: amdgpu: ring vcn_unified_0 uses VM inv eng 0 on hub 8
[ 8090.566137] amdgpu 0000:c1:00.0: amdgpu: ring jpeg_dec_0 uses VM inv eng 1 on hub 8
[ 8090.566138] amdgpu 0000:c1:00.0: amdgpu: ring mes_kiq_3.1.0 uses VM inv eng 13 on hub 0
[ 8090.566138] amdgpu 0000:c1:00.0: amdgpu: ring vpe uses VM inv eng 4 on hub 8
[ 8090.581880] amdgpu 0000:c1:00.0: amdgpu: GPU reset(1) succeeded!
[ 8090.581897] amdgpu 0000:c1:00.0: [drm] device wedged, but recovered through reset
[ 8090.601494] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
[ 8091.716934] rfkill: input handler enabled
[ 8092.985740] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[ 8093.078911] rfkill: input handler disabled
[ 8093.730516] usb 1-1: reset full-speed USB device number 2 using xhci_hcd
[ 8291.129988] usb 1-1: reset full-speed USB device number 2 using xhci_hcd
[ 8295.171015] rfkill: input handler enabled
[ 8295.802120] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[ 8295.854868] rfkill: input handler disabled
[ 8297.742476] hid-generic 0003:32AC:0002.0008: hiddev96,hidraw0: USB HID v1.11 Device [Framework HDMI Expansion Card] on usb-0000:c3:00.0-1/input1

would the coredump help to debug?

**Comment by schung-amd** [comment]
I have access to hardware to repro this now so I'll take a look this week. Out of curiosity, what kernel version are you on? I see some internal reports of similar issues that were resolved by ROCm 6.4.4 (which has mainline support for gfx1150) installed with --no-dkms and kernel 6.14, although I know many non-Ubuntu users are on kernel versions beyond this and it is inconvenient to downgrade.

> would the coredump help to debug?

Potentially, if it's convenient to provide.

**Comment by dattrax** [comment]
kernel is 6.17.0-0.rc7.250924gcec1e6e5d1ab3.58.fc44.x86_64

I did check the path for the coredump, but it wasn't there.  I guess it never got created or was removed when I rebooted

**Comment by dattrax** [comment]
I updated my framework desktop (gfx1151) to fedora rawhide, which is the same as my framework13 (gfx1150) setup running the same version of Comfyui etc. and both have 128GB of unified RAM.  I think they should be as close as possible in terms of features only the laptop variation is the gfx1150 with the 15w power profile.

Anyway the desktop ran fine and didn't crash taking roughly 8mins for a QWEN-WAN2.2 combo.

The only difference I can see between the crashing version (laptop) and working is I was able to use the CI nightlys for the gfx1151, whereas I needed to build my own for gfx1150, so I could have messed something up here.

My next experiment is to build a combined gfx115x-igpu package and install the same version on both to see what happens

**Comment by schung-amd** [comment]
Trying to repro this, but running into some build failures; I think the issue on my end is just that I don't have enough RAM on my test system, will try to procure a system with more.

e: In the meanwhile if you just want to get things working you can try [ROCm on Ryzen](https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/) which has gfx1150 support, although that doesn't address the TheRock specific issue at hand.

**Comment by schung-amd** [comment]
I've been informed that we've seen a similar error signature with Stable Diffusion and Flux on gfx1150. Those issues are resolved by  the kernel patch https://github.com/torvalds/linux/commit/1fb710793ce2619223adffaf981b1ff13cd48f17, which is set to be merged into the mainline kernel 6.18-rc1 by Oct 27. You can test with this fix to see if it also addresses the issue here, and we'll track the patch until it lands in the Fedora kernel.

**Comment by dattrax** [comment]
I've Linux fedora 6.18.0-0.rc2.251022g552c50713f273.25.fc44.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 22 17:13:26 UTC 2025 x86_64 GNU/Linux, so I think I should be good.  I don't think the nightly builds for gfx1150 are generating torch etc. yet, so I'll need to get a build myself

**Comment by dattrax** [comment]
I've built a version from today ([3e3f834](https://github.com/ROCm/TheRock/commit/3e3f834ff81aa91b0dc721bb1aa2d3206b7d50c4))

With the 6.18.0-0.rc2.251022g552c50713f273.25.fc44.x86_64 kernel which I believe should have the fix and I'm still seeing

[ 4755.054815] amdgpu 0000:c1:00.0: amdgpu: GPU reset(19) succeeded!
[ 4755.054829] amdgpu 0000:c1:00.0: [drm] device wedged, but recovered through reset
[ 4769.345656] amdgpu 0000:c1:00.0: amdgpu: MES failed to respond to msg=REMOVE_QUEUE
[ 4769.345662] amdgpu 0000:c1:00.0: amdgpu: failed to remove hardware queue from MES, doorbell=0x1202
[ 4769.345664] amdgpu 0000:c1:00.0: amdgpu: MES might be in unrecoverable state, issue a GPU reset
[ 4769.345667] amdgpu 0000:c1:00.0: amdgpu: Failed to remove queue 2
[ 4769.345688] amdgpu 0000:c1:00.0: amdgpu: GPU reset begin!. Source:  3
[ 4769.345733] amdgpu 0000:c1:00.0: amdgpu: MES failed to respond to msg=REMOVE_QUEUE
[ 4769.345734] amdgpu 0000:c1:00.0: amdgpu: failed to remove hardware queue from MES, doorbell=0x1002
[ 4769.345735] amdgpu 0000:c1:00.0: amdgpu: MES might be in unrecoverable state, issue a GPU reset
[ 4769.345736] amdgpu 0000:c1:00.0: amdgpu: Failed to remove queue 1
[ 4769.345736] amdgpu 0000:c1:00.0: amdgpu: Failed to remove queue 0
[ 4769.345779] amdgpu 0000:c1:00.0: amdgpu: Dumping IP State
[ 4769.347172] amdgpu 0000:c1:00.0: amdgpu: Dumping IP State Completed
[ 4769.402127] amdgpu 0000:c1:00.0: amdgpu: MODE2 reset
[ 4769.424622] amdgpu 0000:c1:00.0: amdgpu: GPU reset succeeded, trying to resume
[ 4769.424961] [drm] PCIE GART of 512M enabled (table at 0x0000008000F00000).

So either the kernel doesn't have the fix yet or something is still not working

**Comment by dattrax** [comment]
and tested the v2-staging builds from aws and these do the same

**Comment by schung-amd** [comment]
Thanks for checking @dattrax. My attention has been pulled to a priority issue at the moment but I will verify and update here as soon as I am able to.

**Comment by dattrax** [comment]
FWIW, I’m getting the same crash on my framework desktop 128gb with gfx1151

**Comment by schung-amd** [comment]
Thanks for the info. Same OS and kernel version on the gfx1151 system?

e: Also, did you build TheRock from source or is this with the pip or tarball releases? I'm having trouble building TheRock on our gfx1150 test machine due to limited memory, will try to repro with the nightly tarball.

**Comment by schung-amd** [comment]
Are you using one of the ComfyUI default workflows for Wan 2.2? And what attention method are you using?

**Comment by schung-amd** [comment]
FWIW I'm not seeing this issue on a gfx1151 desktop system with ComfyUI's Wan 2.2 5B video generation template on Ubuntu 24.04 with the latest kernel there, TheRock torch wheels, and quad attention. I'll have to set up Fedora on our test system when it's not in use to repro this in an environment closer to yours. Ideally I would also have liked to test pytorch attention but the torch wheels I used were not built with support, so I'll try various other wheels (for example, the ones suggested by the mainline ROCm install instructions).

**Comment by dattrax** [comment]
my kernel is

Linux fedora 6.18.0-0.rc4.251104gc9cfc122f0371.38.fc44.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov  4 16:11:05 UTC 2025 x86_64 GNU/Linux

I removed my older install and cloned Comyui and pip installed everything from new.

Loading ComfyUI's Wan 2.2 5B video generation template as you did caused https://github.com/comfyanonymous/ComfyUI/issues/10277

however using qwen image to text example did work

My main issue is now is with longer running models such as qwen vl which doesn't have an example.  I'll retry this now I've reinstalled.

**Comment by dattrax** [comment]
using https://github.com/1038lab/ComfyUI-QwenVL

with the Qwen3-VL-4B-Thinking was OK, but I have 128GB unified RAM so should be able to load a bigger model.  Qwen3-VL-32B-Thinking was enough to trigger the crash

**Comment by schung-amd** [comment]
> Loading ComfyUI's Wan 2.2 5B video generation template as you did caused https://github.com/comfyanonymous/ComfyUI/issues/10277

Is this with quad attention set? I also see that issue with the default attention method (split attention) and this seems to be a known issue with torch >2.7. I had to set `--use-quad-cross-attention` to run it.

**Comment by schung-amd** [comment]
For the crash with the larger model, can you post the dmesg log? You can also try setting `export ROCBLAS_USE_HIPBLASLT=0` and `export ROCBLAS_USE_HIPBLASLT_BATCHED=0`, which is a workaround for a similar issue.

e: Can you also run the crashing workload with `AMD_LOG_LEVEL=4` and post the output around the crash?

**Comment by dattrax** [comment]
I was able to get ComfyUI's Wan 2.2 5B running with `--use-quad-cross-attention`

As far as the larger models I increased the GTT to 96GB and I was able to run qwen vl 32B instruct.  Some of the other qwen3 vl models fail for other reasons, but this is some progress.

`GRUB_CMDLINE_LINUX="rhgb quiet ttm.page_pool_size=24576000 ttm.pages_limit=24576000"`

I'll do some more testing and see if I can get back to the kernel crash

**Comment by dattrax** [comment]
so for instance the 32B thinking model crashed with `Loading checkpoint shards: 100%|█████████| 14/14 [00:25<00:00,  1.83s/it]
Model loaded successfully.
Memory access fault by GPU node-1 (Agent handle: 0x555f7f2ef9a0) on address 0x7f5e85f56000. Reason: Page not present or supervisor privilege.
Aborted                    (core dumped) python main.py --use-quad-cross-attention
`


[ 1008.330834] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32773)
[ 1008.330841] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5578 thread python pid 5578
[ 1008.330842] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f5e85f94000 from client 10
[ 1008.330844] amdgpu 0000:c2:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00801031
[ 1008.330845] amdgpu 0000:c2:00.0: amdgpu: 	 Faulty UTCL2 client ID: TCP (0x8)
[ 1008.330846] amdgpu 0000:c2:00.0: amdgpu: 	 MORE_FAULTS: 0x1
[ 1008.330846] amdgpu 0000:c2:00.0: amdgpu: 	 WALKER_ERROR: 0x0
[ 1008.330847] amdgpu 0000:c2:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x3
[ 1008.330847] amdgpu 0000:c2:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
[ 1008.330848] amdgpu 0000:c2:00.0: amdgpu: 	 RW: 0x0
[ 1008.330858] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32773)
[ 1008.330859] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5578 thread python pid 5578
[ 1008.330859] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f5e85f72000 from client 10
[ 1008.330862] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32773)
[ 1008.330863] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5578 thread python pid 5578
[ 1008.330863] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f5e85f7c000 from client 10
[ 1008.330866] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32773)
[ 1008.330867] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5578 thread python pid 5578
[ 1008.330867] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f5e85f62000 from client 10
[ 1008.330869] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32773)
[ 1008.330870] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5578 thread python pid 5578
[ 1008.330870] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f5e85f61000 from client 10
[ 1008.330873] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32773)
[ 1008.330873] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5578 thread python pid 5578
[ 1008.330874] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f5e85f59000 from client 10
[ 1008.330876] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32773)
[ 1008.330876] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5578 thread python pid 5578
[ 1008.330877] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f5e85f84000 from client 10
[ 1008.330879] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32773)
[ 1008.330880] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5578 thread python pid 5578
[ 1008.330880] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f5e85f74000 from client 10
[ 1008.330885] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:24 vmid:8 pasid:32773)
[ 1008.330885] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5578 thread python pid 5578
[ 1008.330886] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f5e85f56000 from client 10
[ 1010.886850] amdgpu 0000:c2:00.0: amdgpu: MES failed to respond to msg=SUSPEND
[ 1010.886858] amdgpu 0000:c2:00.0: amdgpu: failed to suspend all gangs
[ 1010.886859] amdgpu 0000:c2:00.0: amdgpu: failed to suspend gangs from MES
[ 1010.886860] amdgpu 0000:c2:00.0: amdgpu: MES might be in unrecoverable state, issue a GPU reset
[ 1010.886863] amdgpu 0000:c2:00.0: amdgpu: Suspending all queues failed
[ 1010.886875] amdgpu 0000:c2:00.0: amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 0, priv 1, wave_id 0, simd_id 0, wgp_id 0
[ 1010.886881] amdgpu 0000:c2:00.0: amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 0, priv 1, wave_id 0, simd_id 0, wgp_id 0
[ 1010.886885] amdgpu 0000:c2:00.0: amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 0, priv 1, wave_id 0, simd_id 0, wgp_id 0
[ 1010.886887] amdgpu 0000:c2:00.0: amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 0, priv 1, wave_id 0, simd_id 0, wgp_id 0
[ 1010.886889] amdgpu 0000:c2:00.0: amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 0, priv 1, wave_id 0, simd_id 0, wgp_id 0
[ 1010.886891] amdgpu 0000:c2:00.0: amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 0, priv 1, wave_id 0, simd_id 0, wgp_id 0
[ 1010.886894] amdgpu 0000:c2:00.0: amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 0, priv 1, wave_id 0, simd_id 0, wgp_id 0
[ 1010.886896] amdgpu 0000:c2:00.0: amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 0, priv 1, wave_id 0, simd_id 0, wgp_id 0
[ 1010.886900] amdgpu 0000:c2:00.0: amdgpu: GPU reset begin!. Source:  3
[ 1010.886929] amdgpu 0000:c2:00.0: amdgpu: remove_all_kfd_queues_mes: Failed to remove queue 2 for dev 35971
[ 1010.886974] amdgpu 0000:c2:00.0: amdgpu: Dumping IP State
[ 1010.889094] amdgpu 0000:c2:00.0: amdgpu: Dumping IP State Completed
[ 1011.338322] amdgpu 0000:c2:00.0: amdgpu: MODE2 reset
[ 1011.371475] amdgpu 0000:c2:00.0: amdgpu: GPU reset succeeded, trying to resume
[ 1011.371889] [drm] PCIE GART of 512M enabled (table at 0x000000801FB00000).
[ 1011.371965] amdgpu 0000:c2:00.0: amdgpu: [drm] AMDGPU device coredump file has been created
[ 1011.371966] amdgpu 0000:c2:00.0: amdgpu: [drm] Check your /sys/class/drm/card1/device/devcoredump/data
[ 1011.371969] amdgpu 0000:c2:00.0: amdgpu: SMU is resuming...
[ 1011.385410] amdgpu 0000:c2:00.0: amdgpu: SMU is resumed successfully!
[ 1011.407436] amdgpu 0000:c2:00.0: amdgpu: [drm] DMUB hardware initialized: version=0x09003100
[ 1011.439675] amdgpu 0000:c2:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
[ 1011.439677] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
[ 1011.439678] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
[ 1011.439679] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 6 on hub 0
[ 1011.439680] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 7 on hub 0
[ 1011.439680] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 8 on hub 0
[ 1011.439681] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 9 on hub 0
[ 1011.439682] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 10 on hub 0
[ 1011.439682] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 11 on hub 0
[ 1011.439683] amdgpu 0000:c2:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
[ 1011.439684] amdgpu 0000:c2:00.0: amdgpu: ring vcn_unified_0 uses VM inv eng 0 on hub 8
[ 1011.439684] amdgpu 0000:c2:00.0: amdgpu: ring vcn_unified_1 uses VM inv eng 1 on hub 8
[ 1011.439685] amdgpu 0000:c2:00.0: amdgpu: ring jpeg_dec_0 uses VM inv eng 4 on hub 8
[ 1011.439686] amdgpu 0000:c2:00.0: amdgpu: ring jpeg_dec_1 uses VM inv eng 6 on hub 8
[ 1011.439686] amdgpu 0000:c2:00.0: amdgpu: ring mes_kiq_3.1.0 uses VM inv eng 13 on hub 0
[ 1011.439687] amdgpu 0000:c2:00.0: amdgpu: ring vpe uses VM inv eng 7 on hub 8
[ 1011.451675] amdgpu 0000:c2:00.0: amdgpu: GPU reset(1) succeeded!
[ 1011.451685] amdgpu 0000:c2:00.0: [drm] device wedged, but recovered through reset
[ 1044.588853] amdgpu 0000:c2:00.0: amdgpu: MES failed to respond to msg=REMOVE_QUEUE
[ 1044.588859] amdgpu 0000:c2:00.0: amdgpu: failed to remove hardware queue from MES, doorbell=0x1202
[ 1044.588861] amdgpu 0000:c2:00.0: amdgpu: MES might be in unrecoverable state, issue a GPU reset
[ 1044.588865] amdgpu 0000:c2:00.0: amdgpu: Failed to remove queue 2
[ 1044.588886] amdgpu 0000:c2:00.0: amdgpu: GPU reset begin!. Source:  3
[ 1044.588944] amdgpu 0000:c2:00.0: amdgpu: MES failed to respond to msg=REMOVE_QUEUE
[ 1044.588945] amdgpu 0000:c2:00.0: amdgpu: failed to remove hardware queue from MES, doorbell=0x1002
[ 1044.588945] amdgpu 0000:c2:00.0: amdgpu: MES might be in unrecoverable state, issue a GPU reset
[ 1044.588946] amdgpu 0000:c2:00.0: amdgpu: Failed to remove queue 1
[ 1044.588947] amdgpu 0000:c2:00.0: amdgpu: Failed to remove queue 0
[ 1044.588986] amdgpu 0000:c2:00.0: amdgpu: Dumping IP State
[ 1044.594824] amdgpu 0000:c2:00.0: amdgpu: Dumping IP State Completed
[ 1044.621729] amdgpu 0000:c2:00.0: amdgpu: MODE2 reset
[ 1044.655265] amdgpu 0000:c2:00.0: amdgpu: GPU reset succeeded, trying to resume
[ 1044.655655] [drm] PCIE GART of 512M enabled (table at 0x000000801FB00000).
[ 1044.655684] amdgpu 0000:c2:00.0: amdgpu: [drm] AMDGPU device coredump file has been created
[ 1044.655684] amdgpu 0000:c2:00.0: amdgpu: [drm] Check your /sys/class/drm/card1/device/devcoredump/data
[ 1044.655686] amdgpu 0000:c2:00.0: amdgpu: SMU is resuming...
[ 1044.663399] amdgpu 0000:c2:00.0: amdgpu: SMU is resumed successfully!
[ 1044.680221] amdgpu 0000:c2:00.0: amdgpu: [drm] DMUB hardware initialized: version=0x09003100
[ 1044.712876] amdgpu 0000:c2:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
[ 1044.712879] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
[ 1044.712880] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
[ 1044.712880] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 6 on hub 0
[ 1044.712881] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 7 on hub 0
[ 1044.712882] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 8 on hub 0
[ 1044.712882] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 9 on hub 0
[ 1044.712883] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 10 on hub 0
[ 1044.712883] amdgpu 0000:c2:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 11 on hub 0
[ 1044.712884] amdgpu 0000:c2:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
[ 1044.712884] amdgpu 0000:c2:00.0: amdgpu: ring vcn_unified_0 uses VM inv eng 0 on hub 8
[ 1044.712885] amdgpu 0000:c2:00.0: amdgpu: ring vcn_unified_1 uses VM inv eng 1 on hub 8
[ 1044.712886] amdgpu 0000:c2:00.0: amdgpu: ring jpeg_dec_0 uses VM inv eng 4 on hub 8
[ 1044.712886] amdgpu 0000:c2:00.0: amdgpu: ring jpeg_dec_1 uses VM inv eng 6 on hub 8
[ 1044.712887] amdgpu 0000:c2:00.0: amdgpu: ring mes_kiq_3.1.0 uses VM inv eng 13 on hub 0
[ 1044.712887] amdgpu 0000:c2:00.0: amdgpu: ring vpe uses VM inv eng 7 on hub 8
[ 1044.723479] amdgpu 0000:c2:00.0: amdgpu: GPU reset(2) succeeded!
[ 1044.723489] amdgpu 0000:c2:00.0: [drm] device wedged, but recovered through reset

**Comment by schung-amd** [comment]
@dattrax Sorry for the delay on this, are you still seeing the same crashes? What quantization are you using? There are some issues we have eyes on that may be related.

e: There are some more kernel updates coming to address this, we'll have more info for you shortly.

**Comment by schung-amd** [comment]
There is a fix we're testing with promising results that we expect to address the majority of these issues: https://github.com/ROCm/rocm-systems/pull/1807. However, this relies on some kernel changes which should be publicly available in the next couple months. I'll update when the timelines for these fixes become clearer.

**Comment by dattrax** [comment]
I think I would call it "unstable"  sometimes its fine and occasionally it'll trip the error, so its usable as it is.

I don't know what the protocol here is.  If you want to close or not, I'll leave with you.

**Comment by schung-amd** [comment]
Thanks for the response, glad to hear it's at least usable. Since we have improvements on the horizon I'm happy to leave this open until they land.

**Comment by dattrax** [comment]
I'm seeing some bad crashes in flux.2 (just released) on gfx1150.  This is just using a default example workflow in comfyui

tested the common workarounds as above, but no joy.  to my untrained eye, it looks like a similar issue as above.

[  110.920352] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:153 vmid:8 pasid:32770)
[  110.920359] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 5912 thread python pid 5912
[  110.920361] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f13885b2000 from client 10
[  110.920363] amdgpu 0000:c2:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00800932
[  110.920364] amdgpu 0000:c2:00.0: amdgpu: 	 Faulty UTCL2 client ID: CPF (0x4)
[  110.920366] amdgpu 0000:c2:00.0: amdgpu: 	 MORE_FAULTS: 0x0
[  110.920366] amdgpu 0000:c2:00.0: amdgpu: 	 WALKER_ERROR: 0x1
[  110.920367] amdgpu 0000:c2:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x3
[  110.920368] amdgpu 0000:c2:00.0: amdgpu: 	 MAPPING_ERROR: 0x1
[  110.920368] amdgpu 0000:c2:00.0: amdgpu: 	 RW: 0x0
[  286.686420] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:153 vmid:8 pasid:32770)
[  286.686432] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 7626 thread python pid 7626
[  286.686434] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f2fb0ec5000 from client 10
[  286.686436] amdgpu 0000:c2:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00800932
[  286.686437] amdgpu 0000:c2:00.0: amdgpu: 	 Faulty UTCL2 client ID: CPF (0x4)
[  286.686438] amdgpu 0000:c2:00.0: amdgpu: 	 MORE_FAULTS: 0x0
[  286.686438] amdgpu 0000:c2:00.0: amdgpu: 	 WALKER_ERROR: 0x1
[  286.686439] amdgpu 0000:c2:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x3
[  286.686439] amdgpu 0000:c2:00.0: amdgpu: 	 MAPPING_ERROR: 0x1
[  286.686440] amdgpu 0000:c2:00.0: amdgpu: 	 RW: 0x0
[  471.128146] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:153 vmid:8 pasid:32770)
[  471.128159] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 8814 thread python pid 8814
[  471.128161] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f1741f41000 from client 10
[  471.128163] amdgpu 0000:c2:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00800932
[  471.128164] amdgpu 0000:c2:00.0: amdgpu: 	 Faulty UTCL2 client ID: CPF (0x4)
[  471.128166] amdgpu 0000:c2:00.0: amdgpu: 	 MORE_FAULTS: 0x0
[  471.128167] amdgpu 0000:c2:00.0: amdgpu: 	 WALKER_ERROR: 0x1
[  471.128167] amdgpu 0000:c2:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x3
[  471.128168] amdgpu 0000:c2:00.0: amdgpu: 	 MAPPING_ERROR: 0x1
[  471.128169] amdgpu 0000:c2:00.0: amdgpu: 	 RW: 0x0
[  557.218592] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:153 vmid:8 pasid:32770)
[  557.218603] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 9152 thread python pid 9152
[  557.218605] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007ff173857000 from client 10
[  557.218607] amdgpu 0000:c2:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00800932
[  557.218608] amdgpu 0000:c2:00.0: amdgpu: 	 Faulty UTCL2 client ID: CPF (0x4)
[  557.218609] amdgpu 0000:c2:00.0: amdgpu: 	 MORE_FAULTS: 0x0
[  557.218610] amdgpu 0000:c2:00.0: amdgpu: 	 WALKER_ERROR: 0x1
[  557.218611] amdgpu 0000:c2:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x3
[  557.218612] amdgpu 0000:c2:00.0: amdgpu: 	 MAPPING_ERROR: 0x1
[  557.218612] amdgpu 0000:c2:00.0: amdgpu: 	 RW: 0x0
[  826.624611] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:153 vmid:8 pasid:32777)
[  826.624618] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 9635 thread python pid 9635
[  826.624620] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f031496f000 from client 10
[  826.624622] amdgpu 0000:c2:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00800932
[  826.624623] amdgpu 0000:c2:00.0: amdgpu: 	 Faulty UTCL2 client ID: CPF (0x4)
[  826.624624] amdgpu 0000:c2:00.0: amdgpu: 	 MORE_FAULTS: 0x0
[  826.624624] amdgpu 0000:c2:00.0: amdgpu: 	 WALKER_ERROR: 0x1
[  826.624624] amdgpu 0000:c2:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x3
[  826.624625] amdgpu 0000:c2:00.0: amdgpu: 	 MAPPING_ERROR: 0x1
[  826.624625] amdgpu 0000:c2:00.0: amdgpu: 	 RW: 0x0
[  890.072122] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:153 vmid:8 pasid:32777)
[  890.072135] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 10063 thread python pid 10063
[  890.072137] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f8f63b6f000 from client 10
[ 1489.429199] amdgpu 0000:c2:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:153 vmid:8 pasid:32770)
[ 1489.429212] amdgpu 0000:c2:00.0: amdgpu:  Process python pid 11194 thread python pid 11194
[ 1489.429215] amdgpu 0000:c2:00.0: amdgpu:   in page starting at address 0x00007f852f325000 from client 10

**Comment by schung-amd** [comment]
Which kernel version? The aforementioned improvement/fix is in 6.18-rc6 (see commit https://github.com/torvalds/linux/commit/d15deafab5d722afb9e2f83c5edcdef9d9d98bd1). If you can test this patch with https://github.com/ROCm/rocm-systems/pull/1807, let me know if it helps or not.

**Comment by dattrax** [comment]
now on Linux fedora 6.18.0-0.rc7.58.fc44.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 24 15:19:54 UTC 2025 x86_64 GNU/Linux

I'll grab the patch and let you know

**Comment by dattrax** [comment]
Unfortunately, I either built it incorrectly or the patch didn't work.

**Comment by hammmmy** [comment]
Just found out that https://github.com/ROCm/rocm-systems/pull/1807 isn't yet available in the nightlies https://github.com/ROCm/TheRock/pull/2338. We would have to wait a little longer.

**Comment by dattrax** [comment]
> Just found out that [ROCm/rocm-systems#1807](https://github.com/ROCm/rocm-systems/pull/1807) isn't yet available in the nightlies [#2338](https://github.com/ROCm/TheRock/pull/2338). We would have to wait a little longer.

I did pull the patch and build myself, but whether I have everything required or not is a different matter.  Is the patch only applicable when the rocm-systems is also updated?  I'm guessing from this comment that this is the case.

**Comment by schung-amd** [comment]
Checking back in here; is this issue still seen with ROCm 7.11 or 7.2 and latest kernel version?

**Comment by dattrax** [comment]
I think its OK now
